spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/incidentdb}
    username: ${DB_USERNAME:incident_user}
    password: ${DB_PASSWORD:incident_pass}

  flyway:
    enabled: true
    baseline-on-migrate: true

  jpa:
    hibernate:
      ddl-auto: validate # Changing from 'update' to 'validate' for professional enviroments
    show-sql: true     # Prints SQL queries to the console
    properties:
      hibernate:
        format_sql: true

  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

    consumer:
      group-id: ${KAFKA_CONSUMER_GROUP_ID:incident-service-analysis-consumer}
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer

      properties:
        spring.json.value.default.type: com.example.incident_service.messaging.event.IncidentAnalyzedEvent
        spring.json.trusted.packages: com.example.incident_service.messaging.event

management:
  endpoints:
    web:
      exposure:
        include: health,info

ai-service:
  base-url: ${AI_SERVICE_BASE_URL:http://localhost:8000}